# .goreleaser.yml
project_name: falcon

builds:
  - id: linux_amd64
    goos: linux
    goarch: amd64
    binary: falcon_linux_amd64
  - id: darwin_amd64
    goos: darwin
    goarch: amd64
    binary: falcon_darwin_amd64
  - id: windows_amd64
    goos: windows
    goarch: amd64
    binary: falcon_windows_amd64

archives:
  - id: golang-cross
    builds:
      - linux-amd64
      - darwin-amd64
      - windows_amd64
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    format: tar.gz
    wrap_in_directory: true

release:
  github:
    token: "{{ .Env.GITHUB_TOKEN }}"
    draft: true
    prerelease: true