steps:
# git authentication
- name: "gcr.io/cloud-builders/git"
  id: git ssh authentication
  secretEnv: ["SSH_KEY"]
  entrypoint: "bash"
  args:
  - -c
  - |
    echo "$$SSH_KEY" >> /root/.ssh/id_rsa
    chmod 400 /root/.ssh/id_rsa
    cp known_hosts.github /root/.ssh/known_hosts
  volumes:
  - name: "ssh"
    path: /root/.ssh

# build docker image
- name: "gcr.io/cloud-builders/docker"
  id: build-docker-iamge
  args: ["build", "-t", "asia-southeast1-docker.pkg.dev/${PROJECT_ID}/band-feeder/$_SERVICE_NAME:$SHORT_SHA", "."]

# push docker image in GCR
- name: "gcr.io/cloud-builders/docker"
  id: push-docker-image-to-gcr
  args: ["push", "asia-southeast1-docker.pkg.dev/${PROJECT_ID}/band-feeder/$_SERVICE_NAME:$SHORT_SHA"]

  # install yq
- name: gcr.io/cloud-builders/wget
  args:
  - "-qO"
  - /workspace/yq
  - "https://github.com/mikefarah/yq/releases/latest/download/yq_linux_amd64"

# update image based on SHORT_SHA and push in manifest repo
- name: "gcr.io/cloud-builders/gcloud"
  id: update-image
  entrypoint: /bin/sh
  secretEnv: ["SSH_KEY"]
  args:
  - "-c"
  - |
    chmod +x /workspace/yq
    git clone git@github.com:bandprotocol/band-feeder-gke-manifest-testnet.git -b ${_CD_BRANCH}
    cd band-feeder-gke-manifest-testnet/helm-values/playground

    sed -i -e "/^image:/,/tag:/{/^\([[:space:]]*tag: \).*/s//\1"\"${SHORT_SHA}\""/}" poc-falcon.yaml
    toml=`cat /workspace/config.toml` /workspace/yq -i '.configMap.json = strenv(toml) ' poc-falcon.yaml


    echo "Pushing changes to k8s manifest repo ..."
    git config --global user.name "cloudbuild-commit"
    git config --global user.email "cloudbuild-commit@gmail.com"
    git add -A
    git status
    git commit -m "Updated image tag based on ${SHORT_SHA} for ${_SERVICE_NAME}"
    git pull --rebase
    until git push git@github.com:bandprotocol/band-feeder-gke-manifest-testnet.git ${_CD_BRANCH}
    do
      git pull --rebase
      git push git@github.com:bandprotocol/band-feeder-gke-manifest-testnet.git ${_CD_BRANCH}
    done
  volumes:
  - name: "ssh"
    path: /root/.ssh

substitutions:
  _SERVICE_NAME: poc-falcon
  _CD_BRANCH: poc-production

options:
  logging: CLOUD_LOGGING_ONLY
  machineType: "E2_HIGHCPU_8"
  dynamic_substitutions: true

availableSecrets:
  secretManager:
  - versionName: projects/${PROJECT_ID}/secrets/github-token/versions/latest
    env: "SSH_KEY"
