[global]
log_level = ''
checking_packet_interval = 60000000000
sync_tunnels_interval = 60000000000
max_checking_packet_penalty_duration = 300000000000
penalty_exponential_factor = 1.1

[bandchain]
rpc_endpoints = ['https://rpc.band-v3-testnet.bandchain.org/']
liveliness_checking_interval = 1800000000000
timeout = 5

[target_chains]

[target_chains.holesky-testnet]
endpoints = ['https://ethereum-holesky-rpc.publicnode.com']
chain_type = 'evm'
max_retry = 3
query_timeout = 3000000000
execute_timeout = 0
chain_id = 17000
tunnel_router_address = '0xD3F452702484c9Fe7889F820B01BF7B0E20b221B'
block_confirmation = 1
waiting_tx_duration = 90000000000
liveliness_checking_interval = 1800000000000
max_priority_fee = 100000000
max_base_fee = 100000000
checking_tx_interval = 3000000000
gas_type = 'eip1559'
gas_multiplier = 1.3
