// Code generated by MockGen. DO NOT EDIT.
// Source: relayer/chains/flow/client.go
//
// Generated by this command:
//
//	mockgen -source=relayer/chains/flow/client.go -mock_names Client=MockFlowClient -package mocks -destination internal/relayertest/mocks/chain_flow_client.go
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	big "math/big"
	reflect "reflect"
	time "time"

	flow "github.com/onflow/flow-go-sdk"
	gomock "go.uber.org/mock/gomock"
)

// MockFlowClient is a mock of Client interface.
type MockFlowClient struct {
	ctrl     *gomock.Controller
	recorder *MockFlowClientMockRecorder
	isgomock struct{}
}

// MockFlowClientMockRecorder is the mock recorder for MockFlowClient.
type MockFlowClientMockRecorder struct {
	mock *MockFlowClient
}

// NewMockFlowClient creates a new mock instance.
func NewMockFlowClient(ctrl *gomock.Controller) *MockFlowClient {
	mock := &MockFlowClient{ctrl: ctrl}
	mock.recorder = &MockFlowClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockFlowClient) EXPECT() *MockFlowClientMockRecorder {
	return m.recorder
}

// BroadcastTx mocks base method.
func (m *MockFlowClient) BroadcastTx(ctx context.Context, txBlob []byte) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BroadcastTx", ctx, txBlob)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// BroadcastTx indicates an expected call of BroadcastTx.
func (mr *MockFlowClientMockRecorder) BroadcastTx(ctx, txBlob any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BroadcastTx", reflect.TypeOf((*MockFlowClient)(nil).BroadcastTx), ctx, txBlob)
}

// CheckAndConnect mocks base method.
func (m *MockFlowClient) CheckAndConnect(ctx context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CheckAndConnect", ctx)
	ret0, _ := ret[0].(error)
	return ret0
}

// CheckAndConnect indicates an expected call of CheckAndConnect.
func (mr *MockFlowClientMockRecorder) CheckAndConnect(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CheckAndConnect", reflect.TypeOf((*MockFlowClient)(nil).CheckAndConnect), ctx)
}

// Connect mocks base method.
func (m *MockFlowClient) Connect(ctx context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Connect", ctx)
	ret0, _ := ret[0].(error)
	return ret0
}

// Connect indicates an expected call of Connect.
func (mr *MockFlowClientMockRecorder) Connect(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Connect", reflect.TypeOf((*MockFlowClient)(nil).Connect), ctx)
}

// GetAccount mocks base method.
func (m *MockFlowClient) GetAccount(ctx context.Context, address string) (*flow.Account, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAccount", ctx, address)
	ret0, _ := ret[0].(*flow.Account)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAccount indicates an expected call of GetAccount.
func (mr *MockFlowClientMockRecorder) GetAccount(ctx, address any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAccount", reflect.TypeOf((*MockFlowClient)(nil).GetAccount), ctx, address)
}

// GetBalance mocks base method.
func (m *MockFlowClient) GetBalance(ctx context.Context, address string) (*big.Int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetBalance", ctx, address)
	ret0, _ := ret[0].(*big.Int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetBalance indicates an expected call of GetBalance.
func (mr *MockFlowClientMockRecorder) GetBalance(ctx, address any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetBalance", reflect.TypeOf((*MockFlowClient)(nil).GetBalance), ctx, address)
}

// GetBlockTimestamp mocks base method.
func (m *MockFlowClient) GetBlockTimestamp(ctx context.Context, txHash string) (*time.Time, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetBlockTimestamp", ctx, txHash)
	ret0, _ := ret[0].(*time.Time)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetBlockTimestamp indicates an expected call of GetBlockTimestamp.
func (mr *MockFlowClientMockRecorder) GetBlockTimestamp(ctx, txHash any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetBlockTimestamp", reflect.TypeOf((*MockFlowClient)(nil).GetBlockTimestamp), ctx, txHash)
}

// GetLatestBlockID mocks base method.
func (m *MockFlowClient) GetLatestBlockID(ctx context.Context) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetLatestBlockID", ctx)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetLatestBlockID indicates an expected call of GetLatestBlockID.
func (mr *MockFlowClientMockRecorder) GetLatestBlockID(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetLatestBlockID", reflect.TypeOf((*MockFlowClient)(nil).GetLatestBlockID), ctx)
}

// GetTxResult mocks base method.
func (m *MockFlowClient) GetTxResult(ctx context.Context, txHash string) (*flow.TransactionResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTxResult", ctx, txHash)
	ret0, _ := ret[0].(*flow.TransactionResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetTxResult indicates an expected call of GetTxResult.
func (mr *MockFlowClientMockRecorder) GetTxResult(ctx, txHash any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTxResult", reflect.TypeOf((*MockFlowClient)(nil).GetTxResult), ctx, txHash)
}

// StartLivelinessCheck mocks base method.
func (m *MockFlowClient) StartLivelinessCheck(ctx context.Context, interval time.Duration) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "StartLivelinessCheck", ctx, interval)
}

// StartLivelinessCheck indicates an expected call of StartLivelinessCheck.
func (mr *MockFlowClientMockRecorder) StartLivelinessCheck(ctx, interval any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "StartLivelinessCheck", reflect.TypeOf((*MockFlowClient)(nil).StartLivelinessCheck), ctx, interval)
}
