// Code generated by MockGen. DO NOT EDIT.
// Source: relayer/chains/xrpl/client.go
//
// Generated by this command:
//
//	mockgen -source=relayer/chains/xrpl/client.go -mock_names Client=MockXRPLClient -package mocks -destination internal/relayertest/mocks/chain_xrpl_client.go
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	big "math/big"
	reflect "reflect"
	time "time"

	transaction "github.com/Peersyst/xrpl-go/xrpl/transaction"
	xrpl "github.com/bandprotocol/falcon/relayer/chains/xrpl"
	gomock "go.uber.org/mock/gomock"
)

// MockXRPLClient is a mock of Client interface.
type MockXRPLClient struct {
	ctrl     *gomock.Controller
	recorder *MockXRPLClientMockRecorder
	isgomock struct{}
}

// MockXRPLClientMockRecorder is the mock recorder for MockXRPLClient.
type MockXRPLClientMockRecorder struct {
	mock *MockXRPLClient
}

// NewMockXRPLClient creates a new mock instance.
func NewMockXRPLClient(ctrl *gomock.Controller) *MockXRPLClient {
	mock := &MockXRPLClient{ctrl: ctrl}
	mock.recorder = &MockXRPLClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockXRPLClient) EXPECT() *MockXRPLClientMockRecorder {
	return m.recorder
}

// Autofill mocks base method.
func (m *MockXRPLClient) Autofill(tx *transaction.FlatTransaction) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Autofill", tx)
	ret0, _ := ret[0].(error)
	return ret0
}

// Autofill indicates an expected call of Autofill.
func (mr *MockXRPLClientMockRecorder) Autofill(tx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Autofill", reflect.TypeOf((*MockXRPLClient)(nil).Autofill), tx)
}

// BroadcastTx mocks base method.
func (m *MockXRPLClient) BroadcastTx(txBlob string) (xrpl.TxResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BroadcastTx", txBlob)
	ret0, _ := ret[0].(xrpl.TxResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// BroadcastTx indicates an expected call of BroadcastTx.
func (mr *MockXRPLClientMockRecorder) BroadcastTx(txBlob any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BroadcastTx", reflect.TypeOf((*MockXRPLClient)(nil).BroadcastTx), txBlob)
}

// CheckAndConnect mocks base method.
func (m *MockXRPLClient) CheckAndConnect() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CheckAndConnect")
	ret0, _ := ret[0].(error)
	return ret0
}

// CheckAndConnect indicates an expected call of CheckAndConnect.
func (mr *MockXRPLClientMockRecorder) CheckAndConnect() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CheckAndConnect", reflect.TypeOf((*MockXRPLClient)(nil).CheckAndConnect))
}

// Connect mocks base method.
func (m *MockXRPLClient) Connect() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Connect")
	ret0, _ := ret[0].(error)
	return ret0
}

// Connect indicates an expected call of Connect.
func (mr *MockXRPLClientMockRecorder) Connect() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Connect", reflect.TypeOf((*MockXRPLClient)(nil).Connect))
}

// GetAccountSequenceNumber mocks base method.
func (m *MockXRPLClient) GetAccountSequenceNumber(account string) (uint32, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAccountSequenceNumber", account)
	ret0, _ := ret[0].(uint32)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAccountSequenceNumber indicates an expected call of GetAccountSequenceNumber.
func (mr *MockXRPLClientMockRecorder) GetAccountSequenceNumber(account any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAccountSequenceNumber", reflect.TypeOf((*MockXRPLClient)(nil).GetAccountSequenceNumber), account)
}

// GetBalance mocks base method.
func (m *MockXRPLClient) GetBalance(account string) (*big.Int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetBalance", account)
	ret0, _ := ret[0].(*big.Int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetBalance indicates an expected call of GetBalance.
func (mr *MockXRPLClientMockRecorder) GetBalance(account any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetBalance", reflect.TypeOf((*MockXRPLClient)(nil).GetBalance), account)
}

// GetLedgerCloseTime mocks base method.
func (m *MockXRPLClient) GetLedgerCloseTime(txHash string) (*time.Time, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetLedgerCloseTime", txHash)
	ret0, _ := ret[0].(*time.Time)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetLedgerCloseTime indicates an expected call of GetLedgerCloseTime.
func (mr *MockXRPLClientMockRecorder) GetLedgerCloseTime(txHash any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetLedgerCloseTime", reflect.TypeOf((*MockXRPLClient)(nil).GetLedgerCloseTime), txHash)
}

// StartLivelinessCheck mocks base method.
func (m *MockXRPLClient) StartLivelinessCheck(ctx context.Context, interval time.Duration) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "StartLivelinessCheck", ctx, interval)
}

// StartLivelinessCheck indicates an expected call of StartLivelinessCheck.
func (mr *MockXRPLClientMockRecorder) StartLivelinessCheck(ctx, interval any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "StartLivelinessCheck", reflect.TypeOf((*MockXRPLClient)(nil).StartLivelinessCheck), ctx, interval)
}
