// Code generated by MockGen. DO NOT EDIT.
// Source: relayer/chains/soroban/client.go
//
// Generated by this command:
//
//	mockgen -source=relayer/chains/soroban/client.go -mock_names Client=MockSorobanClient -package mocks -destination internal/relayertest/mocks/chain_soroban_client.go
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	big "math/big"
	reflect "reflect"
	time "time"

	soroban "github.com/bandprotocol/falcon/relayer/chains/soroban"
	horizon "github.com/stellar/go-stellar-sdk/protocols/horizon"
	gomock "go.uber.org/mock/gomock"
)

// MockSorobanClient is a mock of Client interface.
type MockSorobanClient struct {
	ctrl     *gomock.Controller
	recorder *MockSorobanClientMockRecorder
	isgomock struct{}
}

// MockSorobanClientMockRecorder is the mock recorder for MockSorobanClient.
type MockSorobanClientMockRecorder struct {
	mock *MockSorobanClient
}

// NewMockSorobanClient creates a new mock instance.
func NewMockSorobanClient(ctrl *gomock.Controller) *MockSorobanClient {
	mock := &MockSorobanClient{ctrl: ctrl}
	mock.recorder = &MockSorobanClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSorobanClient) EXPECT() *MockSorobanClientMockRecorder {
	return m.recorder
}

// BroadcastTx mocks base method.
func (m *MockSorobanClient) BroadcastTx(txBlob string) (soroban.TxResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BroadcastTx", txBlob)
	ret0, _ := ret[0].(soroban.TxResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// BroadcastTx indicates an expected call of BroadcastTx.
func (mr *MockSorobanClientMockRecorder) BroadcastTx(txBlob any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BroadcastTx", reflect.TypeOf((*MockSorobanClient)(nil).BroadcastTx), txBlob)
}

// CheckAndConnect mocks base method.
func (m *MockSorobanClient) CheckAndConnect(ctx context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CheckAndConnect", ctx)
	ret0, _ := ret[0].(error)
	return ret0
}

// CheckAndConnect indicates an expected call of CheckAndConnect.
func (mr *MockSorobanClientMockRecorder) CheckAndConnect(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CheckAndConnect", reflect.TypeOf((*MockSorobanClient)(nil).CheckAndConnect), ctx)
}

// Connect mocks base method.
func (m *MockSorobanClient) Connect(ctx context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Connect", ctx)
	ret0, _ := ret[0].(error)
	return ret0
}

// Connect indicates an expected call of Connect.
func (mr *MockSorobanClientMockRecorder) Connect(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Connect", reflect.TypeOf((*MockSorobanClient)(nil).Connect), ctx)
}

// GetAccountSequenceNumber mocks base method.
func (m *MockSorobanClient) GetAccountSequenceNumber(account string) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAccountSequenceNumber", account)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAccountSequenceNumber indicates an expected call of GetAccountSequenceNumber.
func (mr *MockSorobanClientMockRecorder) GetAccountSequenceNumber(account any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAccountSequenceNumber", reflect.TypeOf((*MockSorobanClient)(nil).GetAccountSequenceNumber), account)
}

// GetBalance mocks base method.
func (m *MockSorobanClient) GetBalance(account string) (*big.Int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetBalance", account)
	ret0, _ := ret[0].(*big.Int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetBalance indicates an expected call of GetBalance.
func (mr *MockSorobanClientMockRecorder) GetBalance(account any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetBalance", reflect.TypeOf((*MockSorobanClient)(nil).GetBalance), account)
}

// GetFeeStats mocks base method.
func (m *MockSorobanClient) GetFeeStats() (horizon.FeeStats, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetFeeStats")
	ret0, _ := ret[0].(horizon.FeeStats)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetFeeStats indicates an expected call of GetFeeStats.
func (mr *MockSorobanClientMockRecorder) GetFeeStats() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetFeeStats", reflect.TypeOf((*MockSorobanClient)(nil).GetFeeStats))
}

// GetLedgerCloseTime mocks base method.
func (m *MockSorobanClient) GetLedgerCloseTime(ledgerIndex uint64) (*time.Time, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetLedgerCloseTime", ledgerIndex)
	ret0, _ := ret[0].(*time.Time)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetLedgerCloseTime indicates an expected call of GetLedgerCloseTime.
func (mr *MockSorobanClientMockRecorder) GetLedgerCloseTime(ledgerIndex any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetLedgerCloseTime", reflect.TypeOf((*MockSorobanClient)(nil).GetLedgerCloseTime), ledgerIndex)
}

// GetTransactionStatus mocks base method.
func (m *MockSorobanClient) GetTransactionStatus(txHash string) (horizon.Transaction, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTransactionStatus", txHash)
	ret0, _ := ret[0].(horizon.Transaction)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetTransactionStatus indicates an expected call of GetTransactionStatus.
func (mr *MockSorobanClientMockRecorder) GetTransactionStatus(txHash any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTransactionStatus", reflect.TypeOf((*MockSorobanClient)(nil).GetTransactionStatus), txHash)
}

// StartLivelinessCheck mocks base method.
func (m *MockSorobanClient) StartLivelinessCheck(ctx context.Context, interval time.Duration) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "StartLivelinessCheck", ctx, interval)
}

// StartLivelinessCheck indicates an expected call of StartLivelinessCheck.
func (mr *MockSorobanClientMockRecorder) StartLivelinessCheck(ctx, interval any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "StartLivelinessCheck", reflect.TypeOf((*MockSorobanClient)(nil).StartLivelinessCheck), ctx, interval)
}
