// Code generated by MockGen. DO NOT EDIT.
// Source: relayer/chains/config.go
//
// Generated by this command:
//
//	mockgen -source=relayer/chains/config.go -package mocks -destination internal/relayertest/mocks/chain_provider_config.go
//

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	chains "github.com/bandprotocol/falcon/relayer/chains"
	types "github.com/bandprotocol/falcon/relayer/chains/types"
	logger "github.com/bandprotocol/falcon/relayer/logger"
	wallet "github.com/bandprotocol/falcon/relayer/wallet"
	gomock "go.uber.org/mock/gomock"
)

// MockChainProviderConfig is a mock of ChainProviderConfig interface.
type MockChainProviderConfig struct {
	ctrl     *gomock.Controller
	recorder *MockChainProviderConfigMockRecorder
	isgomock struct{}
}

// MockChainProviderConfigMockRecorder is the mock recorder for MockChainProviderConfig.
type MockChainProviderConfigMockRecorder struct {
	mock *MockChainProviderConfig
}

// NewMockChainProviderConfig creates a new mock instance.
func NewMockChainProviderConfig(ctrl *gomock.Controller) *MockChainProviderConfig {
	mock := &MockChainProviderConfig{ctrl: ctrl}
	mock.recorder = &MockChainProviderConfigMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockChainProviderConfig) EXPECT() *MockChainProviderConfigMockRecorder {
	return m.recorder
}

// GetChainType mocks base method.
func (m *MockChainProviderConfig) GetChainType() types.ChainType {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetChainType")
	ret0, _ := ret[0].(types.ChainType)
	return ret0
}

// GetChainType indicates an expected call of GetChainType.
func (mr *MockChainProviderConfigMockRecorder) GetChainType() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetChainType", reflect.TypeOf((*MockChainProviderConfig)(nil).GetChainType))
}

// NewChainProvider mocks base method.
func (m *MockChainProviderConfig) NewChainProvider(chainName string, log logger.ZapLogger, wallet wallet.Wallet) (chains.ChainProvider, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "NewChainProvider", chainName, log, wallet)
	ret0, _ := ret[0].(chains.ChainProvider)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// NewChainProvider indicates an expected call of NewChainProvider.
func (mr *MockChainProviderConfigMockRecorder) NewChainProvider(chainName, log, wallet any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "NewChainProvider", reflect.TypeOf((*MockChainProviderConfig)(nil).NewChainProvider), chainName, log, wallet)
}

// Validate mocks base method.
func (m *MockChainProviderConfig) Validate() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Validate")
	ret0, _ := ret[0].(error)
	return ret0
}

// Validate indicates an expected call of Validate.
func (mr *MockChainProviderConfigMockRecorder) Validate() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Validate", reflect.TypeOf((*MockChainProviderConfig)(nil).Validate))
}
