// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.35.2
// 	protoc        v6.33.1
// source: proto/fkms/v1/signer.proto

package fkmsv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SignEvmRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Address   string `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"`
	TxMessage []byte `protobuf:"bytes,2,opt,name=tx_message,json=txMessage,proto3" json:"tx_message,omitempty"`
	Tss       *Tss   `protobuf:"bytes,3,opt,name=tss,proto3" json:"tss,omitempty"`
}

func (x *SignEvmRequest) Reset() {
	*x = SignEvmRequest{}
	mi := &file_proto_fkms_v1_signer_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SignEvmRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SignEvmRequest) ProtoMessage() {}

func (x *SignEvmRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_fkms_v1_signer_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SignEvmRequest.ProtoReflect.Descriptor instead.
func (*SignEvmRequest) Descriptor() ([]byte, []int) {
	return file_proto_fkms_v1_signer_proto_rawDescGZIP(), []int{0}
}

func (x *SignEvmRequest) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *SignEvmRequest) GetTxMessage() []byte {
	if x != nil {
		return x.TxMessage
	}
	return nil
}

func (x *SignEvmRequest) GetTss() *Tss {
	if x != nil {
		return x.Tss
	}
	return nil
}

type SignEvmResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Signature []byte `protobuf:"bytes,1,opt,name=signature,proto3" json:"signature,omitempty"`
}

func (x *SignEvmResponse) Reset() {
	*x = SignEvmResponse{}
	mi := &file_proto_fkms_v1_signer_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SignEvmResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SignEvmResponse) ProtoMessage() {}

func (x *SignEvmResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_fkms_v1_signer_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SignEvmResponse.ProtoReflect.Descriptor instead.
func (*SignEvmResponse) Descriptor() ([]byte, []int) {
	return file_proto_fkms_v1_signer_proto_rawDescGZIP(), []int{1}
}

func (x *SignEvmResponse) GetSignature() []byte {
	if x != nil {
		return x.Signature
	}
	return nil
}

type SignXrplRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	SignerPayload *XrplSignerPayload `protobuf:"bytes,1,opt,name=signer_payload,json=signerPayload,proto3" json:"signer_payload,omitempty"`
	Tss           *Tss               `protobuf:"bytes,2,opt,name=tss,proto3" json:"tss,omitempty"`
}

func (x *SignXrplRequest) Reset() {
	*x = SignXrplRequest{}
	mi := &file_proto_fkms_v1_signer_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SignXrplRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SignXrplRequest) ProtoMessage() {}

func (x *SignXrplRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_fkms_v1_signer_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SignXrplRequest.ProtoReflect.Descriptor instead.
func (*SignXrplRequest) Descriptor() ([]byte, []int) {
	return file_proto_fkms_v1_signer_proto_rawDescGZIP(), []int{2}
}

func (x *SignXrplRequest) GetSignerPayload() *XrplSignerPayload {
	if x != nil {
		return x.SignerPayload
	}
	return nil
}

func (x *SignXrplRequest) GetTss() *Tss {
	if x != nil {
		return x.Tss
	}
	return nil
}

type SignXrplResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TxBlob []byte `protobuf:"bytes,1,opt,name=tx_blob,json=txBlob,proto3" json:"tx_blob,omitempty"`
}

func (x *SignXrplResponse) Reset() {
	*x = SignXrplResponse{}
	mi := &file_proto_fkms_v1_signer_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SignXrplResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SignXrplResponse) ProtoMessage() {}

func (x *SignXrplResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_fkms_v1_signer_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SignXrplResponse.ProtoReflect.Descriptor instead.
func (*SignXrplResponse) Descriptor() ([]byte, []int) {
	return file_proto_fkms_v1_signer_proto_rawDescGZIP(), []int{3}
}

func (x *SignXrplResponse) GetTxBlob() []byte {
	if x != nil {
		return x.TxBlob
	}
	return nil
}

type GetSignerAddressesRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *GetSignerAddressesRequest) Reset() {
	*x = GetSignerAddressesRequest{}
	mi := &file_proto_fkms_v1_signer_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSignerAddressesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSignerAddressesRequest) ProtoMessage() {}

func (x *GetSignerAddressesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_fkms_v1_signer_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSignerAddressesRequest.ProtoReflect.Descriptor instead.
func (*GetSignerAddressesRequest) Descriptor() ([]byte, []int) {
	return file_proto_fkms_v1_signer_proto_rawDescGZIP(), []int{4}
}

type GetSignerAddressesResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Addresses []string `protobuf:"bytes,1,rep,name=addresses,proto3" json:"addresses,omitempty"`
}

func (x *GetSignerAddressesResponse) Reset() {
	*x = GetSignerAddressesResponse{}
	mi := &file_proto_fkms_v1_signer_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSignerAddressesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSignerAddressesResponse) ProtoMessage() {}

func (x *GetSignerAddressesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_fkms_v1_signer_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSignerAddressesResponse.ProtoReflect.Descriptor instead.
func (*GetSignerAddressesResponse) Descriptor() ([]byte, []int) {
	return file_proto_fkms_v1_signer_proto_rawDescGZIP(), []int{5}
}

func (x *GetSignerAddressesResponse) GetAddresses() []string {
	if x != nil {
		return x.Addresses
	}
	return nil
}

type XrplSignerPayload struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Signals         []*Signal `protobuf:"bytes,1,rep,name=signals,proto3" json:"signals,omitempty"`
	Account         string    `protobuf:"bytes,2,opt,name=account,proto3" json:"account,omitempty"`
	OracleId        uint64    `protobuf:"varint,3,opt,name=oracle_id,json=oracleId,proto3" json:"oracle_id,omitempty"`
	Fee             string    `protobuf:"bytes,4,opt,name=fee,proto3" json:"fee,omitempty"`
	Sequence        uint64    `protobuf:"varint,5,opt,name=sequence,proto3" json:"sequence,omitempty"`
	LastUpdatedTime uint64    `protobuf:"varint,6,opt,name=last_updated_time,json=lastUpdatedTime,proto3" json:"last_updated_time,omitempty"`
}

func (x *XrplSignerPayload) Reset() {
	*x = XrplSignerPayload{}
	mi := &file_proto_fkms_v1_signer_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *XrplSignerPayload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*XrplSignerPayload) ProtoMessage() {}

func (x *XrplSignerPayload) ProtoReflect() protoreflect.Message {
	mi := &file_proto_fkms_v1_signer_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use XrplSignerPayload.ProtoReflect.Descriptor instead.
func (*XrplSignerPayload) Descriptor() ([]byte, []int) {
	return file_proto_fkms_v1_signer_proto_rawDescGZIP(), []int{6}
}

func (x *XrplSignerPayload) GetSignals() []*Signal {
	if x != nil {
		return x.Signals
	}
	return nil
}

func (x *XrplSignerPayload) GetAccount() string {
	if x != nil {
		return x.Account
	}
	return ""
}

func (x *XrplSignerPayload) GetOracleId() uint64 {
	if x != nil {
		return x.OracleId
	}
	return 0
}

func (x *XrplSignerPayload) GetFee() string {
	if x != nil {
		return x.Fee
	}
	return ""
}

func (x *XrplSignerPayload) GetSequence() uint64 {
	if x != nil {
		return x.Sequence
	}
	return 0
}

func (x *XrplSignerPayload) GetLastUpdatedTime() uint64 {
	if x != nil {
		return x.LastUpdatedTime
	}
	return 0
}

type Signal struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	SignalId string `protobuf:"bytes,1,opt,name=signal_id,json=signalId,proto3" json:"signal_id,omitempty"`
	Price    uint64 `protobuf:"varint,2,opt,name=price,proto3" json:"price,omitempty"`
}

func (x *Signal) Reset() {
	*x = Signal{}
	mi := &file_proto_fkms_v1_signer_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Signal) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Signal) ProtoMessage() {}

func (x *Signal) ProtoReflect() protoreflect.Message {
	mi := &file_proto_fkms_v1_signer_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Signal.ProtoReflect.Descriptor instead.
func (*Signal) Descriptor() ([]byte, []int) {
	return file_proto_fkms_v1_signer_proto_rawDescGZIP(), []int{7}
}

func (x *Signal) GetSignalId() string {
	if x != nil {
		return x.SignalId
	}
	return ""
}

func (x *Signal) GetPrice() uint64 {
	if x != nil {
		return x.Price
	}
	return 0
}

type Tss struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Message    []byte `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	RandomAddr []byte `protobuf:"bytes,2,opt,name=random_addr,json=randomAddr,proto3" json:"random_addr,omitempty"`
	SignatureS []byte `protobuf:"bytes,3,opt,name=signature_s,json=signatureS,proto3" json:"signature_s,omitempty"`
}

func (x *Tss) Reset() {
	*x = Tss{}
	mi := &file_proto_fkms_v1_signer_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Tss) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Tss) ProtoMessage() {}

func (x *Tss) ProtoReflect() protoreflect.Message {
	mi := &file_proto_fkms_v1_signer_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Tss.ProtoReflect.Descriptor instead.
func (*Tss) Descriptor() ([]byte, []int) {
	return file_proto_fkms_v1_signer_proto_rawDescGZIP(), []int{8}
}

func (x *Tss) GetMessage() []byte {
	if x != nil {
		return x.Message
	}
	return nil
}

func (x *Tss) GetRandomAddr() []byte {
	if x != nil {
		return x.RandomAddr
	}
	return nil
}

func (x *Tss) GetSignatureS() []byte {
	if x != nil {
		return x.SignatureS
	}
	return nil
}

var File_proto_fkms_v1_signer_proto protoreflect.FileDescriptor

var file_proto_fkms_v1_signer_proto_rawDesc = []byte{
	0x0a, 0x1a, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x66, 0x6b, 0x6d, 0x73, 0x2f, 0x76, 0x31, 0x2f,
	0x73, 0x69, 0x67, 0x6e, 0x65, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x07, 0x66, 0x6b,
	0x6d, 0x73, 0x2e, 0x76, 0x31, 0x22, 0x69, 0x0a, 0x0e, 0x53, 0x69, 0x67, 0x6e, 0x45, 0x76, 0x6d,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x18, 0x0a, 0x07, 0x61, 0x64, 0x64, 0x72, 0x65,
	0x73, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x61, 0x64, 0x64, 0x72, 0x65, 0x73,
	0x73, 0x12, 0x1d, 0x0a, 0x0a, 0x74, 0x78, 0x5f, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x09, 0x74, 0x78, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65,
	0x12, 0x1e, 0x0a, 0x03, 0x74, 0x73, 0x73, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0c, 0x2e,
	0x66, 0x6b, 0x6d, 0x73, 0x2e, 0x76, 0x31, 0x2e, 0x54, 0x73, 0x73, 0x52, 0x03, 0x74, 0x73, 0x73,
	0x22, 0x2f, 0x0a, 0x0f, 0x53, 0x69, 0x67, 0x6e, 0x45, 0x76, 0x6d, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x12, 0x1c, 0x0a, 0x09, 0x73, 0x69, 0x67, 0x6e, 0x61, 0x74, 0x75, 0x72, 0x65,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x09, 0x73, 0x69, 0x67, 0x6e, 0x61, 0x74, 0x75, 0x72,
	0x65, 0x22, 0x74, 0x0a, 0x0f, 0x53, 0x69, 0x67, 0x6e, 0x58, 0x72, 0x70, 0x6c, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x12, 0x41, 0x0a, 0x0e, 0x73, 0x69, 0x67, 0x6e, 0x65, 0x72, 0x5f, 0x70,
	0x61, 0x79, 0x6c, 0x6f, 0x61, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x66,
	0x6b, 0x6d, 0x73, 0x2e, 0x76, 0x31, 0x2e, 0x58, 0x72, 0x70, 0x6c, 0x53, 0x69, 0x67, 0x6e, 0x65,
	0x72, 0x50, 0x61, 0x79, 0x6c, 0x6f, 0x61, 0x64, 0x52, 0x0d, 0x73, 0x69, 0x67, 0x6e, 0x65, 0x72,
	0x50, 0x61, 0x79, 0x6c, 0x6f, 0x61, 0x64, 0x12, 0x1e, 0x0a, 0x03, 0x74, 0x73, 0x73, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x0c, 0x2e, 0x66, 0x6b, 0x6d, 0x73, 0x2e, 0x76, 0x31, 0x2e, 0x54,
	0x73, 0x73, 0x52, 0x03, 0x74, 0x73, 0x73, 0x22, 0x2b, 0x0a, 0x10, 0x53, 0x69, 0x67, 0x6e, 0x58,
	0x72, 0x70, 0x6c, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x17, 0x0a, 0x07, 0x74,
	0x78, 0x5f, 0x62, 0x6c, 0x6f, 0x62, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x06, 0x74, 0x78,
	0x42, 0x6c, 0x6f, 0x62, 0x22, 0x1b, 0x0a, 0x19, 0x47, 0x65, 0x74, 0x53, 0x69, 0x67, 0x6e, 0x65,
	0x72, 0x41, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x65, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x22, 0x3a, 0x0a, 0x1a, 0x47, 0x65, 0x74, 0x53, 0x69, 0x67, 0x6e, 0x65, 0x72, 0x41, 0x64,
	0x64, 0x72, 0x65, 0x73, 0x73, 0x65, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12,
	0x1c, 0x0a, 0x09, 0x61, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x65, 0x73, 0x18, 0x01, 0x20, 0x03,
	0x28, 0x09, 0x52, 0x09, 0x61, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x65, 0x73, 0x22, 0xcf, 0x01,
	0x0a, 0x11, 0x58, 0x72, 0x70, 0x6c, 0x53, 0x69, 0x67, 0x6e, 0x65, 0x72, 0x50, 0x61, 0x79, 0x6c,
	0x6f, 0x61, 0x64, 0x12, 0x29, 0x0a, 0x07, 0x73, 0x69, 0x67, 0x6e, 0x61, 0x6c, 0x73, 0x18, 0x01,
	0x20, 0x03, 0x28, 0x0b, 0x32, 0x0f, 0x2e, 0x66, 0x6b, 0x6d, 0x73, 0x2e, 0x76, 0x31, 0x2e, 0x53,
	0x69, 0x67, 0x6e, 0x61, 0x6c, 0x52, 0x07, 0x73, 0x69, 0x67, 0x6e, 0x61, 0x6c, 0x73, 0x12, 0x18,
	0x0a, 0x07, 0x61, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x07, 0x61, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x12, 0x1b, 0x0a, 0x09, 0x6f, 0x72, 0x61, 0x63,
	0x6c, 0x65, 0x5f, 0x69, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x04, 0x52, 0x08, 0x6f, 0x72, 0x61,
	0x63, 0x6c, 0x65, 0x49, 0x64, 0x12, 0x10, 0x0a, 0x03, 0x66, 0x65, 0x65, 0x18, 0x04, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x03, 0x66, 0x65, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x73, 0x65, 0x71, 0x75, 0x65,
	0x6e, 0x63, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x04, 0x52, 0x08, 0x73, 0x65, 0x71, 0x75, 0x65,
	0x6e, 0x63, 0x65, 0x12, 0x2a, 0x0a, 0x11, 0x6c, 0x61, 0x73, 0x74, 0x5f, 0x75, 0x70, 0x64, 0x61,
	0x74, 0x65, 0x64, 0x5f, 0x74, 0x69, 0x6d, 0x65, 0x18, 0x06, 0x20, 0x01, 0x28, 0x04, 0x52, 0x0f,
	0x6c, 0x61, 0x73, 0x74, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x64, 0x54, 0x69, 0x6d, 0x65, 0x22,
	0x3b, 0x0a, 0x06, 0x53, 0x69, 0x67, 0x6e, 0x61, 0x6c, 0x12, 0x1b, 0x0a, 0x09, 0x73, 0x69, 0x67,
	0x6e, 0x61, 0x6c, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x73, 0x69,
	0x67, 0x6e, 0x61, 0x6c, 0x49, 0x64, 0x12, 0x14, 0x0a, 0x05, 0x70, 0x72, 0x69, 0x63, 0x65, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x04, 0x52, 0x05, 0x70, 0x72, 0x69, 0x63, 0x65, 0x22, 0x61, 0x0a, 0x03,
	0x54, 0x73, 0x73, 0x12, 0x18, 0x0a, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x0c, 0x52, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x1f, 0x0a,
	0x0b, 0x72, 0x61, 0x6e, 0x64, 0x6f, 0x6d, 0x5f, 0x61, 0x64, 0x64, 0x72, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x0c, 0x52, 0x0a, 0x72, 0x61, 0x6e, 0x64, 0x6f, 0x6d, 0x41, 0x64, 0x64, 0x72, 0x12, 0x1f,
	0x0a, 0x0b, 0x73, 0x69, 0x67, 0x6e, 0x61, 0x74, 0x75, 0x72, 0x65, 0x5f, 0x73, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x0c, 0x52, 0x0a, 0x73, 0x69, 0x67, 0x6e, 0x61, 0x74, 0x75, 0x72, 0x65, 0x53, 0x32,
	0xeb, 0x01, 0x0a, 0x0b, 0x46, 0x6b, 0x6d, 0x73, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12,
	0x3c, 0x0a, 0x07, 0x53, 0x69, 0x67, 0x6e, 0x45, 0x76, 0x6d, 0x12, 0x17, 0x2e, 0x66, 0x6b, 0x6d,
	0x73, 0x2e, 0x76, 0x31, 0x2e, 0x53, 0x69, 0x67, 0x6e, 0x45, 0x76, 0x6d, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x1a, 0x18, 0x2e, 0x66, 0x6b, 0x6d, 0x73, 0x2e, 0x76, 0x31, 0x2e, 0x53, 0x69,
	0x67, 0x6e, 0x45, 0x76, 0x6d, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x3f, 0x0a,
	0x08, 0x53, 0x69, 0x67, 0x6e, 0x58, 0x72, 0x70, 0x6c, 0x12, 0x18, 0x2e, 0x66, 0x6b, 0x6d, 0x73,
	0x2e, 0x76, 0x31, 0x2e, 0x53, 0x69, 0x67, 0x6e, 0x58, 0x72, 0x70, 0x6c, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x1a, 0x19, 0x2e, 0x66, 0x6b, 0x6d, 0x73, 0x2e, 0x76, 0x31, 0x2e, 0x53, 0x69,
	0x67, 0x6e, 0x58, 0x72, 0x70, 0x6c, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x5d,
	0x0a, 0x12, 0x47, 0x65, 0x74, 0x53, 0x69, 0x67, 0x6e, 0x65, 0x72, 0x41, 0x64, 0x64, 0x72, 0x65,
	0x73, 0x73, 0x65, 0x73, 0x12, 0x22, 0x2e, 0x66, 0x6b, 0x6d, 0x73, 0x2e, 0x76, 0x31, 0x2e, 0x47,
	0x65, 0x74, 0x53, 0x69, 0x67, 0x6e, 0x65, 0x72, 0x41, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x65,
	0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x23, 0x2e, 0x66, 0x6b, 0x6d, 0x73, 0x2e,
	0x76, 0x31, 0x2e, 0x47, 0x65, 0x74, 0x53, 0x69, 0x67, 0x6e, 0x65, 0x72, 0x41, 0x64, 0x64, 0x72,
	0x65, 0x73, 0x73, 0x65, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x42, 0x35, 0x5a,
	0x33, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x62, 0x61, 0x6e, 0x64,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x2f, 0x66, 0x61, 0x6c, 0x63, 0x6f, 0x6e, 0x2f,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x66, 0x6b, 0x6d, 0x73, 0x2f, 0x76, 0x31, 0x3b, 0x66, 0x6b,
	0x6d, 0x73, 0x76, 0x31, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_proto_fkms_v1_signer_proto_rawDescOnce sync.Once
	file_proto_fkms_v1_signer_proto_rawDescData = file_proto_fkms_v1_signer_proto_rawDesc
)

func file_proto_fkms_v1_signer_proto_rawDescGZIP() []byte {
	file_proto_fkms_v1_signer_proto_rawDescOnce.Do(func() {
		file_proto_fkms_v1_signer_proto_rawDescData = protoimpl.X.CompressGZIP(file_proto_fkms_v1_signer_proto_rawDescData)
	})
	return file_proto_fkms_v1_signer_proto_rawDescData
}

var file_proto_fkms_v1_signer_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_proto_fkms_v1_signer_proto_goTypes = []any{
	(*SignEvmRequest)(nil),             // 0: fkms.v1.SignEvmRequest
	(*SignEvmResponse)(nil),            // 1: fkms.v1.SignEvmResponse
	(*SignXrplRequest)(nil),            // 2: fkms.v1.SignXrplRequest
	(*SignXrplResponse)(nil),           // 3: fkms.v1.SignXrplResponse
	(*GetSignerAddressesRequest)(nil),  // 4: fkms.v1.GetSignerAddressesRequest
	(*GetSignerAddressesResponse)(nil), // 5: fkms.v1.GetSignerAddressesResponse
	(*XrplSignerPayload)(nil),          // 6: fkms.v1.XrplSignerPayload
	(*Signal)(nil),                     // 7: fkms.v1.Signal
	(*Tss)(nil),                        // 8: fkms.v1.Tss
}
var file_proto_fkms_v1_signer_proto_depIdxs = []int32{
	8, // 0: fkms.v1.SignEvmRequest.tss:type_name -> fkms.v1.Tss
	6, // 1: fkms.v1.SignXrplRequest.signer_payload:type_name -> fkms.v1.XrplSignerPayload
	8, // 2: fkms.v1.SignXrplRequest.tss:type_name -> fkms.v1.Tss
	7, // 3: fkms.v1.XrplSignerPayload.signals:type_name -> fkms.v1.Signal
	0, // 4: fkms.v1.FkmsService.SignEvm:input_type -> fkms.v1.SignEvmRequest
	2, // 5: fkms.v1.FkmsService.SignXrpl:input_type -> fkms.v1.SignXrplRequest
	4, // 6: fkms.v1.FkmsService.GetSignerAddresses:input_type -> fkms.v1.GetSignerAddressesRequest
	1, // 7: fkms.v1.FkmsService.SignEvm:output_type -> fkms.v1.SignEvmResponse
	3, // 8: fkms.v1.FkmsService.SignXrpl:output_type -> fkms.v1.SignXrplResponse
	5, // 9: fkms.v1.FkmsService.GetSignerAddresses:output_type -> fkms.v1.GetSignerAddressesResponse
	7, // [7:10] is the sub-list for method output_type
	4, // [4:7] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_proto_fkms_v1_signer_proto_init() }
func file_proto_fkms_v1_signer_proto_init() {
	if File_proto_fkms_v1_signer_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_proto_fkms_v1_signer_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_fkms_v1_signer_proto_goTypes,
		DependencyIndexes: file_proto_fkms_v1_signer_proto_depIdxs,
		MessageInfos:      file_proto_fkms_v1_signer_proto_msgTypes,
	}.Build()
	File_proto_fkms_v1_signer_proto = out.File
	file_proto_fkms_v1_signer_proto_rawDesc = nil
	file_proto_fkms_v1_signer_proto_goTypes = nil
	file_proto_fkms_v1_signer_proto_depIdxs = nil
}
