// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v6.33.1
// source: proto/fkms/v1/signer.proto

package fkmsv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	FkmsService_SignEvm_FullMethodName            = "/fkms.v1.FkmsService/SignEvm"
	FkmsService_SignXrpl_FullMethodName           = "/fkms.v1.FkmsService/SignXrpl"
	FkmsService_GetSignerAddresses_FullMethodName = "/fkms.v1.FkmsService/GetSignerAddresses"
)

// FkmsServiceClient is the client API for FkmsService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type FkmsServiceClient interface {
	SignEvm(ctx context.Context, in *SignEvmRequest, opts ...grpc.CallOption) (*SignEvmResponse, error)
	SignXrpl(ctx context.Context, in *SignXrplRequest, opts ...grpc.CallOption) (*SignXrplResponse, error)
	GetSignerAddresses(ctx context.Context, in *GetSignerAddressesRequest, opts ...grpc.CallOption) (*GetSignerAddressesResponse, error)
}

type fkmsServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewFkmsServiceClient(cc grpc.ClientConnInterface) FkmsServiceClient {
	return &fkmsServiceClient{cc}
}

func (c *fkmsServiceClient) SignEvm(ctx context.Context, in *SignEvmRequest, opts ...grpc.CallOption) (*SignEvmResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SignEvmResponse)
	err := c.cc.Invoke(ctx, FkmsService_SignEvm_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *fkmsServiceClient) SignXrpl(ctx context.Context, in *SignXrplRequest, opts ...grpc.CallOption) (*SignXrplResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SignXrplResponse)
	err := c.cc.Invoke(ctx, FkmsService_SignXrpl_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *fkmsServiceClient) GetSignerAddresses(ctx context.Context, in *GetSignerAddressesRequest, opts ...grpc.CallOption) (*GetSignerAddressesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetSignerAddressesResponse)
	err := c.cc.Invoke(ctx, FkmsService_GetSignerAddresses_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// FkmsServiceServer is the server API for FkmsService service.
// All implementations must embed UnimplementedFkmsServiceServer
// for forward compatibility.
type FkmsServiceServer interface {
	SignEvm(context.Context, *SignEvmRequest) (*SignEvmResponse, error)
	SignXrpl(context.Context, *SignXrplRequest) (*SignXrplResponse, error)
	GetSignerAddresses(context.Context, *GetSignerAddressesRequest) (*GetSignerAddressesResponse, error)
	mustEmbedUnimplementedFkmsServiceServer()
}

// UnimplementedFkmsServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedFkmsServiceServer struct{}

func (UnimplementedFkmsServiceServer) SignEvm(context.Context, *SignEvmRequest) (*SignEvmResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SignEvm not implemented")
}
func (UnimplementedFkmsServiceServer) SignXrpl(context.Context, *SignXrplRequest) (*SignXrplResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SignXrpl not implemented")
}
func (UnimplementedFkmsServiceServer) GetSignerAddresses(context.Context, *GetSignerAddressesRequest) (*GetSignerAddressesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetSignerAddresses not implemented")
}
func (UnimplementedFkmsServiceServer) mustEmbedUnimplementedFkmsServiceServer() {}
func (UnimplementedFkmsServiceServer) testEmbeddedByValue()                     {}

// UnsafeFkmsServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to FkmsServiceServer will
// result in compilation errors.
type UnsafeFkmsServiceServer interface {
	mustEmbedUnimplementedFkmsServiceServer()
}

func RegisterFkmsServiceServer(s grpc.ServiceRegistrar, srv FkmsServiceServer) {
	// If the following call pancis, it indicates UnimplementedFkmsServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&FkmsService_ServiceDesc, srv)
}

func _FkmsService_SignEvm_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SignEvmRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FkmsServiceServer).SignEvm(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FkmsService_SignEvm_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FkmsServiceServer).SignEvm(ctx, req.(*SignEvmRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FkmsService_SignXrpl_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SignXrplRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FkmsServiceServer).SignXrpl(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FkmsService_SignXrpl_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FkmsServiceServer).SignXrpl(ctx, req.(*SignXrplRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FkmsService_GetSignerAddresses_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetSignerAddressesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FkmsServiceServer).GetSignerAddresses(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FkmsService_GetSignerAddresses_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FkmsServiceServer).GetSignerAddresses(ctx, req.(*GetSignerAddressesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// FkmsService_ServiceDesc is the grpc.ServiceDesc for FkmsService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var FkmsService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "fkms.v1.FkmsService",
	HandlerType: (*FkmsServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SignEvm",
			Handler:    _FkmsService_SignEvm_Handler,
		},
		{
			MethodName: "SignXrpl",
			Handler:    _FkmsService_SignXrpl_Handler,
		},
		{
			MethodName: "GetSignerAddresses",
			Handler:    _FkmsService_GetSignerAddresses_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/fkms/v1/signer.proto",
}
