// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.29.3
// source: proto/kms/signer.proto

package kms

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	KmsEvmService_SignEvm_FullMethodName = "/kms.KmsEvmService/SignEvm"
)

// KmsEvmServiceClient is the client API for KmsEvmService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type KmsEvmServiceClient interface {
	SignEvm(ctx context.Context, in *SignEvmRequest, opts ...grpc.CallOption) (*SignEvmResponse, error)
}

type kmsEvmServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewKmsEvmServiceClient(cc grpc.ClientConnInterface) KmsEvmServiceClient {
	return &kmsEvmServiceClient{cc}
}

func (c *kmsEvmServiceClient) SignEvm(ctx context.Context, in *SignEvmRequest, opts ...grpc.CallOption) (*SignEvmResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SignEvmResponse)
	err := c.cc.Invoke(ctx, KmsEvmService_SignEvm_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// KmsEvmServiceServer is the server API for KmsEvmService service.
// All implementations must embed UnimplementedKmsEvmServiceServer
// for forward compatibility.
type KmsEvmServiceServer interface {
	SignEvm(context.Context, *SignEvmRequest) (*SignEvmResponse, error)
	mustEmbedUnimplementedKmsEvmServiceServer()
}

// UnimplementedKmsEvmServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedKmsEvmServiceServer struct{}

func (UnimplementedKmsEvmServiceServer) SignEvm(context.Context, *SignEvmRequest) (*SignEvmResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SignEvm not implemented")
}
func (UnimplementedKmsEvmServiceServer) mustEmbedUnimplementedKmsEvmServiceServer() {}
func (UnimplementedKmsEvmServiceServer) testEmbeddedByValue()                       {}

// UnsafeKmsEvmServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to KmsEvmServiceServer will
// result in compilation errors.
type UnsafeKmsEvmServiceServer interface {
	mustEmbedUnimplementedKmsEvmServiceServer()
}

func RegisterKmsEvmServiceServer(s grpc.ServiceRegistrar, srv KmsEvmServiceServer) {
	// If the following call pancis, it indicates UnimplementedKmsEvmServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&KmsEvmService_ServiceDesc, srv)
}

func _KmsEvmService_SignEvm_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SignEvmRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KmsEvmServiceServer).SignEvm(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: KmsEvmService_SignEvm_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KmsEvmServiceServer).SignEvm(ctx, req.(*SignEvmRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// KmsEvmService_ServiceDesc is the grpc.ServiceDesc for KmsEvmService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var KmsEvmService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "kms.KmsEvmService",
	HandlerType: (*KmsEvmServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SignEvm",
			Handler:    _KmsEvmService_SignEvm_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/kms/signer.proto",
}
