// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.35.2
// 	protoc        v5.29.3
// source: proto/kms/v1/signer.proto

package kmsv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SignEvmRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Address string `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"`
	Message []byte `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
}

func (x *SignEvmRequest) Reset() {
	*x = SignEvmRequest{}
	mi := &file_proto_kms_v1_signer_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SignEvmRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SignEvmRequest) ProtoMessage() {}

func (x *SignEvmRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_kms_v1_signer_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SignEvmRequest.ProtoReflect.Descriptor instead.
func (*SignEvmRequest) Descriptor() ([]byte, []int) {
	return file_proto_kms_v1_signer_proto_rawDescGZIP(), []int{0}
}

func (x *SignEvmRequest) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *SignEvmRequest) GetMessage() []byte {
	if x != nil {
		return x.Message
	}
	return nil
}

type SignEvmResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Signature []byte `protobuf:"bytes,1,opt,name=signature,proto3" json:"signature,omitempty"`
}

func (x *SignEvmResponse) Reset() {
	*x = SignEvmResponse{}
	mi := &file_proto_kms_v1_signer_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SignEvmResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SignEvmResponse) ProtoMessage() {}

func (x *SignEvmResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_kms_v1_signer_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SignEvmResponse.ProtoReflect.Descriptor instead.
func (*SignEvmResponse) Descriptor() ([]byte, []int) {
	return file_proto_kms_v1_signer_proto_rawDescGZIP(), []int{1}
}

func (x *SignEvmResponse) GetSignature() []byte {
	if x != nil {
		return x.Signature
	}
	return nil
}

type GetSignerAddressesRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *GetSignerAddressesRequest) Reset() {
	*x = GetSignerAddressesRequest{}
	mi := &file_proto_kms_v1_signer_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSignerAddressesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSignerAddressesRequest) ProtoMessage() {}

func (x *GetSignerAddressesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_kms_v1_signer_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSignerAddressesRequest.ProtoReflect.Descriptor instead.
func (*GetSignerAddressesRequest) Descriptor() ([]byte, []int) {
	return file_proto_kms_v1_signer_proto_rawDescGZIP(), []int{2}
}

type GetSignerAddressesResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Addresses []string `protobuf:"bytes,1,rep,name=addresses,proto3" json:"addresses,omitempty"`
}

func (x *GetSignerAddressesResponse) Reset() {
	*x = GetSignerAddressesResponse{}
	mi := &file_proto_kms_v1_signer_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSignerAddressesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSignerAddressesResponse) ProtoMessage() {}

func (x *GetSignerAddressesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_kms_v1_signer_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSignerAddressesResponse.ProtoReflect.Descriptor instead.
func (*GetSignerAddressesResponse) Descriptor() ([]byte, []int) {
	return file_proto_kms_v1_signer_proto_rawDescGZIP(), []int{3}
}

func (x *GetSignerAddressesResponse) GetAddresses() []string {
	if x != nil {
		return x.Addresses
	}
	return nil
}

var File_proto_kms_v1_signer_proto protoreflect.FileDescriptor

var file_proto_kms_v1_signer_proto_rawDesc = []byte{
	0x0a, 0x19, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x6b, 0x6d, 0x73, 0x2f, 0x76, 0x31, 0x2f, 0x73,
	0x69, 0x67, 0x6e, 0x65, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x06, 0x6b, 0x6d, 0x73,
	0x2e, 0x76, 0x31, 0x22, 0x44, 0x0a, 0x0e, 0x53, 0x69, 0x67, 0x6e, 0x45, 0x76, 0x6d, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x18, 0x0a, 0x07, 0x61, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x61, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x12,
	0x18, 0x0a, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0c,
	0x52, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x22, 0x2f, 0x0a, 0x0f, 0x53, 0x69, 0x67,
	0x6e, 0x45, 0x76, 0x6d, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x1c, 0x0a, 0x09,
	0x73, 0x69, 0x67, 0x6e, 0x61, 0x74, 0x75, 0x72, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52,
	0x09, 0x73, 0x69, 0x67, 0x6e, 0x61, 0x74, 0x75, 0x72, 0x65, 0x22, 0x1b, 0x0a, 0x19, 0x47, 0x65,
	0x74, 0x53, 0x69, 0x67, 0x6e, 0x65, 0x72, 0x41, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x65, 0x73,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0x3a, 0x0a, 0x1a, 0x47, 0x65, 0x74, 0x53, 0x69,
	0x67, 0x6e, 0x65, 0x72, 0x41, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x65, 0x73, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x1c, 0x0a, 0x09, 0x61, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73,
	0x65, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x09, 0x52, 0x09, 0x61, 0x64, 0x64, 0x72, 0x65, 0x73,
	0x73, 0x65, 0x73, 0x32, 0xa8, 0x01, 0x0a, 0x0d, 0x4b, 0x6d, 0x73, 0x45, 0x76, 0x6d, 0x53, 0x65,
	0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x3a, 0x0a, 0x07, 0x53, 0x69, 0x67, 0x6e, 0x45, 0x76, 0x6d,
	0x12, 0x16, 0x2e, 0x6b, 0x6d, 0x73, 0x2e, 0x76, 0x31, 0x2e, 0x53, 0x69, 0x67, 0x6e, 0x45, 0x76,
	0x6d, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x17, 0x2e, 0x6b, 0x6d, 0x73, 0x2e, 0x76,
	0x31, 0x2e, 0x53, 0x69, 0x67, 0x6e, 0x45, 0x76, 0x6d, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x12, 0x5b, 0x0a, 0x12, 0x47, 0x65, 0x74, 0x53, 0x69, 0x67, 0x6e, 0x65, 0x72, 0x41, 0x64,
	0x64, 0x72, 0x65, 0x73, 0x73, 0x65, 0x73, 0x12, 0x21, 0x2e, 0x6b, 0x6d, 0x73, 0x2e, 0x76, 0x31,
	0x2e, 0x47, 0x65, 0x74, 0x53, 0x69, 0x67, 0x6e, 0x65, 0x72, 0x41, 0x64, 0x64, 0x72, 0x65, 0x73,
	0x73, 0x65, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x22, 0x2e, 0x6b, 0x6d, 0x73,
	0x2e, 0x76, 0x31, 0x2e, 0x47, 0x65, 0x74, 0x53, 0x69, 0x67, 0x6e, 0x65, 0x72, 0x41, 0x64, 0x64,
	0x72, 0x65, 0x73, 0x73, 0x65, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x42, 0x33,
	0x5a, 0x31, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x62, 0x61, 0x6e,
	0x64, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x2f, 0x66, 0x61, 0x6c, 0x63, 0x6f, 0x6e,
	0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x6b, 0x6d, 0x73, 0x2f, 0x76, 0x31, 0x3b, 0x6b, 0x6d,
	0x73, 0x76, 0x31, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_proto_kms_v1_signer_proto_rawDescOnce sync.Once
	file_proto_kms_v1_signer_proto_rawDescData = file_proto_kms_v1_signer_proto_rawDesc
)

func file_proto_kms_v1_signer_proto_rawDescGZIP() []byte {
	file_proto_kms_v1_signer_proto_rawDescOnce.Do(func() {
		file_proto_kms_v1_signer_proto_rawDescData = protoimpl.X.CompressGZIP(file_proto_kms_v1_signer_proto_rawDescData)
	})
	return file_proto_kms_v1_signer_proto_rawDescData
}

var file_proto_kms_v1_signer_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_proto_kms_v1_signer_proto_goTypes = []any{
	(*SignEvmRequest)(nil),             // 0: kms.v1.SignEvmRequest
	(*SignEvmResponse)(nil),            // 1: kms.v1.SignEvmResponse
	(*GetSignerAddressesRequest)(nil),  // 2: kms.v1.GetSignerAddressesRequest
	(*GetSignerAddressesResponse)(nil), // 3: kms.v1.GetSignerAddressesResponse
}
var file_proto_kms_v1_signer_proto_depIdxs = []int32{
	0, // 0: kms.v1.KmsEvmService.SignEvm:input_type -> kms.v1.SignEvmRequest
	2, // 1: kms.v1.KmsEvmService.GetSignerAddresses:input_type -> kms.v1.GetSignerAddressesRequest
	1, // 2: kms.v1.KmsEvmService.SignEvm:output_type -> kms.v1.SignEvmResponse
	3, // 3: kms.v1.KmsEvmService.GetSignerAddresses:output_type -> kms.v1.GetSignerAddressesResponse
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_kms_v1_signer_proto_init() }
func file_proto_kms_v1_signer_proto_init() {
	if File_proto_kms_v1_signer_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_proto_kms_v1_signer_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_kms_v1_signer_proto_goTypes,
		DependencyIndexes: file_proto_kms_v1_signer_proto_depIdxs,
		MessageInfos:      file_proto_kms_v1_signer_proto_msgTypes,
	}.Build()
	File_proto_kms_v1_signer_proto = out.File
	file_proto_kms_v1_signer_proto_rawDesc = nil
	file_proto_kms_v1_signer_proto_goTypes = nil
	file_proto_kms_v1_signer_proto_depIdxs = nil
}
