name: Tests
on: pull_request

env:
  GOPRIVATE: github.com/bandprotocol/private-chain

jobs:
  falcon-test:
    runs-on: ubuntu-latest
    steps:
      - name: Code checkout
        uses: actions/checkout@v4

      - name: Install Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.22.3"

      - name: Configure git for private modules
        env:
          TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
        run: git config --global url."https://user:${TOKEN}@github.com".insteadOf "https://github.com"

      - name: Check go mod cache
        uses: actions/cache@v4
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-falcon-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-falcon-

      - name: Run falcon tests
        run: go test ./...
