name: 'Release'

on:
  push:
    tags:
      - '*' # Run release on any tag. Will be marked as draft by default anyway.

jobs:
  goreleaser:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.22'

      - name: release publish
        run: make release
      
      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            ./build/falcon_linux_amd64
            ./build/falcon_linux_arm64
            ./build/falcon_darwin_amd64
            ./build/falcon_darwin_arm64
 