name: 'Release'

on:
  push:
    tags:
      - '*' # Run release on any tag. Will be marked as draft by default anyway.

jobs:
  goreleaser:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.22'

      - name: setup release environment
        run: |-
          echo 'GITHUB_TOKEN=${{secrets.GITHUB_TOKEN}}' > .release-env

      - name: release publish
        run: make release

      # upload linux_amd64 binaries  
      - name: upload binaries
        uses: actions/upload-artifact@v4
        with:
          name: falcon_linux_amd64
          path: ./build/falcon_linux_amd64
      
      # upload darwin_amd64 binaries
      - name: upload binaries
        uses: actions/upload-artifact@v4
        with:
          name: falcon_darwin_amd64
          path: ./build/falcon_darwin_amd64

       # upload windows_amd64 binaries
      - name: upload binaries
        uses: actions/upload-artifact@v4
        with:
          name: falcon_windows_amd64
          path: ./build/falcon_windows_amd64


      
